criterion_type: MSELoss
data_shapes:
  inputs_shape: !!python/tuple
  - 900
  - 101
  - 16
  raw_input_tensors_shape: !!python/object/apply:torch.Size
  - !!python/tuple
    - 1000
    - 101
    - 8
    - 2
  targets_shape: !!python/tuple
  - 900
  - 6
data_sizes:
  train_batch_size: 16
  train_dataset_size: 900
  validation_batch_size: 16
  validation_dataset_size: 100
data_sub_cfg:
  input_scaler_config:
    data_max_:
    - 7.961657502164599e-06
    - 0.0002424951089778915
    data_min_:
    - -7.961675692058634e-06
    - -0.00021130948152858764
    data_range_:
    - 1.5923333194223233e-05
    - 0.00045380459050647914
    feature_range: &id004 !!python/tuple
    - -1
    - 1
    min_:
    - 1.1423421097944697e-06
    - -0.06872038780942802
    scale_:
    - 125601.84325763985
    - 4407.183271918544
  merged_config:
    G: 1.0
    L_quad: 1
    L_straight: 1
    apply_avg: true
    com_delta_range: !!python/tuple
    - -5.0e-05
    - 5.0e-05
    config_name: Configuration 1
    delta_range: !!python/tuple
    - 0
    - 5.0e-05
    design_radius: 20.0
    dipole_length_range:
    - 0.2
    - 14.0
    dipole_tilt_angle_range: !!python/tuple
    - 0
    - 0.05
    dipole_tilt_errors: null
    end_rev: 2000
    f: 15
    figs_save_dir: exps/exp_FCNN_1000/run_2025-01-14_08-53-50/figs
    fodo_cell_indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    horizontal_tune_range:
    - 0.1
    - 0.8
    mag_field_range:
    - 0.1
    - 2.0
    n_FODO: 8
    n_field_index: !!python/object/apply:numpy.core.multiarray.scalar
    - &id003 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      2e2/xSWf3D8=
    n_turns: 2000
    num_particles: 10
    p: 5.344286e-19
    particles_sampling_method: from_twiss_params
    planes:
    - x
    - y
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: 2.842884483322954e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: -3.2080855533400726e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: -4.5321306079850484e-06
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -6.186046256441877e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: 5.501961958249008e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: -8.911790882163216e-05
      plane: vertical
      quad_type: defocusing
    quad_tilt_angle_range: !!python/tuple
    - -0.1
    - 0.1
    quad_tilt_errors: null
    random_criterion: normal
    reject_multiple_error_types: false
    sampling_circle_radius: 0.01
    start_rev: 1500
    target_data: quad_misalign_deltas
    total_dipole_bending_angle_range: !!python/tuple
    - 4.71238898038469
    - 6.283185307179586
    use_gpu: true
    use_thin_lens: true
    verbose: true
    vertical_tune_range:
    - 0.1
    - 0.8
    window_size: 10
    x0_mean_std: &id001 !!python/tuple
    - 0.0
    - 0.05
    xp0_mean_std: &id002 !!python/tuple
    - 0.0
    - 0.0
    y0_mean_std: *id001
    yp0_mean_std: *id002
  overridden_base_config:
    B: 0.16680043695380775
    B_rho: 3.336008739076155
    G: 1.0
    L_dipole: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      Rur/ntuPF0A=
    L_drift: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      wHCqUvTU3j8=
    L_quad: 1
    L_straight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      YDhVKXpqD0A=
    Qx: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      uSjQu8QA0j8=
    Qy: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      uijQu8QA0j8=
    config_name: Configuration 1
    design_radius: 20.0
    dipole_tilt_errors: null
    f: 3.336008739076155
    n_Dipoles: 16
    n_FODO: 8
    p: 5.344286e-19
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: 2.842884483322954e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: -3.2080855533400726e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: -4.5321306079850484e-06
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -6.186046256441877e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: 5.501961958249008e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: -8.911790882163216e-05
      plane: vertical
      quad_type: defocusing
    quad_tilt_errors: null
    total_dipole_bending_angle: !!python/object/apply:numpy.core.multiarray.scalar
    - *id003
    - !!binary |
      0iEzf3zZEkA=
  target_scaler_config:
    data_max_:
    - 0.00014724035281687975
    - 0.0001785917265806347
    - 0.00014230232045520097
    - 0.00019378252909518778
    - 0.0001469711132813245
    - 0.0001667942851781845
    data_min_:
    - -0.00015658087795600295
    - -0.00014304244541563094
    - -0.00014822404773440212
    - -0.00017289201787207276
    - -0.00014146484318189323
    - -0.00016891321865841746
    data_range_:
    - 0.0003038212307728827
    - 0.00032163417199626565
    - 0.0002905263681896031
    - 0.00036667454696726054
    - 0.00028843595646321774
    - 0.00033570750383660197
    feature_range: *id004
    min_:
    - 0.030743490556476516
    - -0.11052706540590007
    - 0.02038275326298966
    - -0.05697289707152842
    - -0.01909009600241518
    - 0.006311844257328003
    scale_:
    - 6582.818438699144
    - 6218.244745534132
    - 6884.056729386992
    - 5454.428229452684
    - 6933.94826540999
    - 5957.567159337179
device: cuda
model_parameters:
  hidden_size: 32
  input_size: 1616
  is_bidirectional: null
  num_layers: 1
  output_size: 6
model_type: SimpleFullyConnectedNetwork
network_topology:
  input_shape: !!python/tuple
  - -1
  - 101
  - 16
  output_shape: !!python/tuple
  - -1
  - 6
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  lr: 0.0001
  maximize: false
  weight_decay: 0
optimizer_type: Adam
random_seed: 5396660527711840935
scheduler_params:
  T_max: 1800
  eta_min: 5.0e-10
scheduler_type: CosineAnnealingLR
timestamp: 2025-01-14_09-32-33
training_hyperparameters:
  nb_epoch_log: 10
  num_epochs: 900
training_parameters:
  batch_size: 16
  criterion: MSELoss
  learning_rate: 0.0001
  num_epochs: 900
  optimizer: Adam
  scheduler: CosineAnnealingLR
