criterion_type: MSELoss
data_shapes:
  inputs_shape: !!python/tuple
  - 18
  - 101
  - 16
  raw_input_tensors_shape: !!python/object/apply:torch.Size
  - !!python/tuple
    - 20
    - 101
    - 8
    - 2
  targets_shape: !!python/tuple
  - 18
  - 6
data_sizes:
  train_batch_size: 16
  train_dataset_size: 270
  validation_batch_size: 16
  validation_dataset_size: 300
device: cuda
model_parameters:
  hidden_size: 256
  input_size: 16
  is_bidirectional: true
  num_layers: 1
  output_size: null
model_type: QuadErrorCorrectionLSTM
network_topology:
  input_shape: !!python/tuple
  - -1
  - 101
  - 16
  output_shape: !!python/tuple
  - -1
  - 6
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  lr: 0.001
  maximize: false
  weight_decay: 0
optimizer_type: Adam
random_seed: 2801388963478224027
scheduler_params:
  base_lr: 1.0e-10
  base_momentum: 0.8
  cycle_momentum: true
  max_lr: 0.001
  max_momentum: 0.9
  mode: triangular2
scheduler_type: CyclicLR
timestamp: 2025-01-13_06-31-50
training_hyperparameters:
  nb_epoch_log: 10
  num_epochs: 600
training_parameters:
  batch_size: 16
  criterion: MSELoss
  learning_rate: 0.001
  num_epochs: 600
  optimizer: Adam
  scheduler: CyclicLR
