criterion_type: MSELoss
data_shapes:
  inputs_shape: !!python/tuple
  - 995
  - 100
  - 16
  raw_input_tensors_shape: !!python/object/apply:torch.Size
  - !!python/tuple
    - 1106
    - 100
    - 8
    - 2
  targets_shape: !!python/tuple
  - 995
  - 6
data_sizes:
  train_batch_size: 16
  train_dataset_size: 995
  validation_batch_size: 16
  validation_dataset_size: 111
data_sub_cfg:
  input_scaler_config:
    data_max_:
    - 1.6327069721361746e+37
    - 0.0019176608184352517
    data_min_:
    - -1.6587632766937458e+37
    - -0.0018989009549841285
    data_range_:
    - 3.2914702488299204e+37
    - 0.00381656177341938
    feature_range: &id004 !!python/tuple
    - -1
    - 1
    min_:
    - 0.007916311735411963
    - -0.004915383155010722
    scale_:
    - 6.076311948166558e-38
    - 524.0318691889364
  merged_config:
    B: 0.16680043695380775
    B_rho: 3.336008739076155
    G: 1.0
    L_dipole: !!python/object/apply:numpy._core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      Rur/ntuPF0A=
    L_drift: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      +tHuwhME6T8=
    L_quad: 0.4
    L_straight: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      YDhVKXpqD0A=
    Qx: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      LKqhs6fv3T8=
    Qy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      RWPryA8Bxz8=
    apply_avg: false
    com_delta_range: !!python/tuple
    - -5.0e-05
    - 5.0e-05
    config_name: Configuration 1
    correct_injection_offset: false
    delta_range: !!python/tuple
    - 0
    - 5.0e-05
    design_radius: 20.0
    dipole_length_range:
    - 0.2
    - 14.0
    dipole_tilt_angle_range: !!python/tuple
    - 0
    - 0.05
    dipole_tilt_errors: null
    end_rev: 6000
    f: 3.336008739076155
    figs_save_dir: exps/test/run_2026-03-28_17-15-46/figs
    fodo_cell_indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    horizontal_tune_range:
    - 0.1
    - 0.8
    include_no_error_data: false
    k_errors:
      enabled: true
      k_error_cells:
      - FODO_index: 0
        quad_type: focusing
      - FODO_index: 0
        quad_type: defocusing
      - FODO_index: 1
        quad_type: focusing
      - FODO_index: 1
        quad_type: defocusing
      - FODO_index: 2
        quad_type: focusing
      - FODO_index: 2
        quad_type: defocusing
      - FODO_index: 3
        quad_type: focusing
      - FODO_index: 3
        quad_type: defocusing
      - FODO_index: 4
        quad_type: focusing
      - FODO_index: 4
        quad_type: defocusing
      - FODO_index: 5
        quad_type: focusing
      - FODO_index: 5
        quad_type: defocusing
      - FODO_index: 6
        quad_type: focusing
      - FODO_index: 6
        quad_type: defocusing
      - FODO_index: 7
        quad_type: focusing
      - FODO_index: 7
        quad_type: defocusing
      k_stochastic_jitter_fraction_range: !!python/tuple
      - 0.005
      - 0.01
      k_systemic_drift_fraction_range: !!python/tuple
      - 0.04
      - 0.04
    mag_field_range:
    - 0.1
    - 2.0
    max_iter_per_infer: 2000
    n_Dipoles: 16
    n_FODO: 8
    n_turns: 6000
    num_particles: 300
    p: 5.344286e-19
    particles_sampling_method: from_twiss_params
    planes:
    - x
    - y
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: -1.3513353963286401e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: 4.906792300332081e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: 2.6724617233527e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -4.727268837007195e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: 7.922035390444068e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: 4.2113027715689235e-05
      plane: vertical
      quad_type: defocusing
    quad_tilt_angle_range: !!python/tuple
    - 0
    - 0.01
    quad_tilt_errors:
    - FODO_index: 1
      quad_type: defocusing
      tilt_angle: -0.01810639108296922
    - FODO_index: 3
      quad_type: defocusing
      tilt_angle: -0.012416294544944168
    - FODO_index: 6
      quad_type: defocusing
      tilt_angle: 0.00865629443074866
    random_criterion: normal
    reject_multiple_error_types: false
    sampling_circle_radius: 0.01
    start_rev: 5900
    target_data: quad_misalign_deltas
    total_dipole_bending_angle: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      0iEzf3zZEkA=
    total_dipole_bending_angle_range: !!python/tuple
    - 4.71238898038469
    - 6.283185307179586
    use_gpu_torch: true
    use_thin_lens: true
    verbose: true
    vertical_tune_range:
    - 0.1
    - 0.8
    window_size: 0
    x0_mean_std: &id002 !!python/tuple
    - 0.0
    - 0.05
    xp0_mean_std: &id003 !!python/tuple
    - 0.0
    - 0.0
    y0_mean_std: *id002
    yp0_mean_std: *id003
  overridden_base_config:
    B: 0.16680043695380775
    B_rho: 3.336008739076155
    G: 1.0
    L_dipole: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      Rur/ntuPF0A=
    L_drift: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      +tHuwhME6T8=
    L_quad: 0.4
    L_straight: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      YDhVKXpqD0A=
    Qx: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      LKqhs6fv3T8=
    Qy: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      RWPryA8Bxz8=
    config_name: Configuration 1
    design_radius: 20.0
    dipole_tilt_errors: null
    f: 3.336008739076155
    figs_save_dir: exps/test/run_2026-03-28_17-15-46/figs
    k_errors:
      enabled: true
      k_error_cells:
      - FODO_index: 0
        quad_type: focusing
      - FODO_index: 0
        quad_type: defocusing
      - FODO_index: 1
        quad_type: focusing
      - FODO_index: 1
        quad_type: defocusing
      - FODO_index: 2
        quad_type: focusing
      - FODO_index: 2
        quad_type: defocusing
      - FODO_index: 3
        quad_type: focusing
      - FODO_index: 3
        quad_type: defocusing
      - FODO_index: 4
        quad_type: focusing
      - FODO_index: 4
        quad_type: defocusing
      - FODO_index: 5
        quad_type: focusing
      - FODO_index: 5
        quad_type: defocusing
      - FODO_index: 6
        quad_type: focusing
      - FODO_index: 6
        quad_type: defocusing
      - FODO_index: 7
        quad_type: focusing
      - FODO_index: 7
        quad_type: defocusing
      k_stochastic_jitter_fraction_range: !!python/tuple
      - 0.005
      - 0.01
      k_systemic_drift_fraction_range: !!python/tuple
      - 0.04
      - 0.04
    n_Dipoles: 16
    n_FODO: 8
    p: 5.344286e-19
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: -1.3513353963286401e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: 4.906792300332081e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: 2.6724617233527e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -4.727268837007195e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: 7.922035390444068e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: 4.2113027715689235e-05
      plane: vertical
      quad_type: defocusing
    quad_tilt_errors:
    - FODO_index: 1
      quad_type: defocusing
      tilt_angle: -0.01810639108296922
    - FODO_index: 3
      quad_type: defocusing
      tilt_angle: -0.012416294544944168
    - FODO_index: 6
      quad_type: defocusing
      tilt_angle: 0.00865629443074866
    total_dipole_bending_angle: !!python/object/apply:numpy._core.multiarray.scalar
    - *id001
    - !!binary |
      0iEzf3zZEkA=
  target_scaler_config:
    data_max_:
    - 0.00014904556155670434
    - 0.00013588141882792115
    - 0.00014686402573715895
    - 0.00017248430231120437
    - 0.00017774463049136102
    - 0.00015268019342329353
    data_min_:
    - -0.00016058167966548353
    - -0.0001617393281776458
    - -0.00015472236555069685
    - -0.0001914401800604537
    - -0.0001784472115105018
    - -0.0001937439665198326
    data_range_:
    - 0.0003096272412221879
    - 0.00029762074700556695
    - 0.0003015863912878558
    - 0.0003639244823716581
    - 0.0003561918420018628
    - 0.00034642415994312614
    feature_range: *id004
    min_:
    - 0.03725808511952233
    - 0.08688207932372727
    - 0.02605667908283471
    - 0.05208739358703163
    - 0.001972479254977122
    - 0.11853611221365368
    scale_:
    - 6459.3799696222595
    - 6719.961629430996
    - 6631.598963930225
    - 5495.645654192341
    - 5614.951731515345
    - 5773.269394167971
device: cuda
model_parameters:
  hidden_size: 256
  input_size: 16
  is_bidirectional: true
  num_layers: 1
  output_size: null
model_type: QuadErrorCorrectionLSTM
network_topology:
  input_shape: !!python/tuple
  - -1
  - 100
  - 16
  output_shape: !!python/tuple
  - -1
  - 6
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  lr: 0.001
  maximize: false
  weight_decay: 0
optimizer_type: Adam
random_seed: 3491955018031449298
scheduler_params:
  base_lr: 1.0e-10
  base_momentum: 0.8
  cycle_momentum: true
  max_lr: 0.001
  max_momentum: 0.9
  mode: triangular2
scheduler_type: CyclicLR
timestamp: 2026-03-28_17-15-50
training_hyperparameters:
  nb_epoch_log: 10
  num_epochs: 900
training_parameters:
  batch_size: 16
  criterion: MSELoss
  learning_rate: 0.001
  num_epochs: 900
  optimizer: Adam
  scheduler: CyclicLR
