criterion_type: MSELoss
data_shapes:
  inputs_shape: !!python/tuple
  - 1800
  - 101
  - 16
  raw_input_tensors_shape: !!python/object/apply:torch.Size
  - !!python/tuple
    - 2000
    - 101
    - 8
    - 2
  targets_shape: !!python/tuple
  - 1800
  - 6
data_sizes:
  train_batch_size: 32
  train_dataset_size: 1800
  validation_batch_size: 32
  validation_dataset_size: 200
data_sub_cfg:
  input_scaler_config:
    data_max_:
    - 3.7399051507236436e-05
    - 0.0006240826332941651
    data_min_:
    - -5.4451447795145214e-05
    - -0.0006700024823658168
    data_range_:
    - 9.185049930238165e-05
    - 0.001294085115659982
    feature_range: &id004 !!python/tuple
    - -1
    - 1
    min_:
    - 0.1856538224334574
    - 0.03548441174074757
    scale_:
    - 21774.51418544592
    - 1545.493395911599
  merged_config:
    B: 0.16680043695380775
    B_rho: 3.336008739076155
    G: 1.0
    L_dipole: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      Rur/ntuPF0A=
    L_drift: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +tHuwhME6T8=
    L_quad: 0.4
    L_straight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      YDhVKXpqD0A=
    Qx: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      RWPryA8Bxz8=
    Qy: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Lqqhs6fv3T8=
    apply_avg: true
    com_delta_range: !!python/tuple
    - -5.0e-05
    - 5.0e-05
    config_name: Configuration 1
    correct_injection_offset: false
    delta_range: !!python/tuple
    - 0
    - 5.0e-05
    design_radius: 20.0
    dipole_length_range:
    - 0.2
    - 14.0
    dipole_tilt_angle_range: !!python/tuple
    - 0
    - 0.05
    dipole_tilt_errors: null
    end_rev: 6000
    f: 3.336008739076155
    figs_save_dir: exps/test/run_2025-10-15_11-48-11/figs
    fodo_cell_indices:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    horizontal_tune_range:
    - 0.1
    - 0.8
    mag_field_range:
    - 0.1
    - 2.0
    n_Dipoles: 16
    n_FODO: 8
    n_turns: 6000
    num_particles: 20
    p: 5.344286e-19
    particles_sampling_method: from_twiss_params
    planes:
    - x
    - y
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: -5.155327791892205e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: -8.19655679833852e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: 6.73230777426882e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -4.073461972900956e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: -3.778598272897297e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: -9.943366177596273e-07
      plane: vertical
      quad_type: defocusing
    quad_tilt_angle_range: !!python/tuple
    - 0
    - 0.01
    quad_tilt_errors:
    - FODO_index: 1
      quad_type: defocusing
      tilt_angle: -0.00421480533298954
    - FODO_index: 3
      quad_type: defocusing
      tilt_angle: 0.017174061593180356
    - FODO_index: 6
      quad_type: defocusing
      tilt_angle: -0.005113544228978013
    random_criterion: normal
    reject_multiple_error_types: false
    sampling_circle_radius: 0.01
    start_rev: 5500
    target_data: quad_misalign_deltas
    total_dipole_bending_angle: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      0iEzf3zZEkA=
    total_dipole_bending_angle_range: !!python/tuple
    - 4.71238898038469
    - 6.283185307179586
    use_gpu: true
    use_thin_lens: true
    verbose: true
    vertical_tune_range:
    - 0.1
    - 0.8
    window_size: 10
    x0_mean_std: &id002 !!python/tuple
    - 0.0
    - 0.05
    xp0_mean_std: &id003 !!python/tuple
    - 0.0
    - 0.0
    y0_mean_std: *id002
    yp0_mean_std: *id003
  overridden_base_config:
    B: 0.16680043695380775
    B_rho: 3.336008739076155
    G: 1.0
    L_dipole: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Rur/ntuPF0A=
    L_drift: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      +tHuwhME6T8=
    L_quad: 0.4
    L_straight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      YDhVKXpqD0A=
    Qx: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      RWPryA8Bxz8=
    Qy: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Lqqhs6fv3T8=
    config_name: Configuration 1
    design_radius: 20.0
    dipole_tilt_errors: null
    f: 3.336008739076155
    figs_save_dir: exps/test/run_2025-10-15_11-48-11/figs
    n_Dipoles: 16
    n_FODO: 8
    p: 5.344286e-19
    q: 1.602e-19
    quad_errors:
    - FODO_index: 1
      delta: -5.155327791892205e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 2
      delta: -8.19655679833852e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 3
      delta: 6.73230777426882e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 4
      delta: -4.073461972900956e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 5
      delta: -3.778598272897297e-05
      plane: vertical
      quad_type: defocusing
    - FODO_index: 7
      delta: -9.943366177596273e-07
      plane: vertical
      quad_type: defocusing
    quad_tilt_errors:
    - FODO_index: 1
      quad_type: defocusing
      tilt_angle: -0.00421480533298954
    - FODO_index: 3
      quad_type: defocusing
      tilt_angle: 0.017174061593180356
    - FODO_index: 6
      quad_type: defocusing
      tilt_angle: -0.005113544228978013
    total_dipole_bending_angle: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      0iEzf3zZEkA=
  target_scaler_config:
    data_max_:
    - 0.0001710709766484797
    - 0.00016919751942623407
    - 0.00018466002075001597
    - 0.0001447557151550427
    - 0.00017274924903176725
    - 0.00014830133295617998
    data_min_:
    - -0.00017144731828011572
    - -0.00016300244897138327
    - -0.00019364795298315585
    - -0.0001565674174344167
    - -0.0001578813826199621
    - -0.0001762262254487723
    data_range_:
    - 0.0003425182949285954
    - 0.00033219996839761734
    - 0.0003783079737331718
    - 0.0003013231325894594
    - 0.00033063063165172935
    - 0.0003245275584049523
    feature_range: *id004
    min_:
    - 0.0010987489929976668
    - -0.01864861843525467
    - 0.0237582415840889
    - 0.03919945401426239
    - -0.044968206174757164
    - 0.08604783097571955
    scale_:
    - 5839.104157682844
    - 6020.470169359428
    - 5286.697978538089
    - 6637.392830788465
    - 6049.046302844394
    - 6162.804816422888
device: cuda
model_parameters:
  hidden_size: 256
  input_size: 16
  is_bidirectional: true
  num_layers: 1
  output_size: null
model_type: QuadErrorCorrectionLSTM
network_topology:
  input_shape: !!python/tuple
  - -1
  - 101
  - 16
  output_shape: !!python/tuple
  - -1
  - 6
optimizer_params:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: null
  lr: 0.001
  maximize: false
  weight_decay: 0
optimizer_type: Adam
random_seed: 3057191601642387033
scheduler_params:
  base_lr: 1.0e-10
  base_momentum: 0.8
  cycle_momentum: true
  max_lr: 0.001
  max_momentum: 0.9
  mode: triangular2
scheduler_type: CyclicLR
timestamp: 2025-10-15_11-48-16
training_hyperparameters:
  nb_epoch_log: 10
  num_epochs: 900
training_parameters:
  batch_size: 32
  criterion: MSELoss
  learning_rate: 0.001
  num_epochs: 900
  optimizer: Adam
  scheduler: CyclicLR
